ALTER TABLE wbb1_board ADD icon VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE wbb1_board ADD iconColor VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE wbb1_board ADD iconNew VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE wbb1_board ADD iconNewColor VARCHAR(255) NOT NULL DEFAULT '';
