<?php
namespace wbb\system\board;
use wbb\data\board\BoardList;
use wcf\data\application\Application;
use wcf\system\event\EventHandler;
use wcf\system\io\File;
use wcf\system\style\StyleHandler;
use wcf\system\SingletonFactory;

/**
 * Handles the board icons file.
 * 
 * @author	Matthias Schmidt
 * @copyright	2014 Maasdt
 * @license	Creative Commons Attribution-NonCommercial-ShareAlike <http://creativecommons.org/licenses/by-nc-sa/4.0/legalcode>
 * @package	com.maasdt.wbb.icon
 * @subpackage	system.board
 * @category	Burning Board
 */
class BoardIconHandler extends SingletonFactory {
	/**
	 * Writes the style file with the board icons.
	 */
	public function writeStyleFile() {
		$boardList = new BoardList();
		$boardList->readObjects();
		
		$fileContent = '';
		foreach ($boardList as $board) {
			if (($board->isBoard() || $board->isExternalLink()) && ($board->icon || $board->iconColor || $board->iconNew || $board->iconNewColor)) {
				$fileContent .= "\tli[data-board-id=\"".$board->boardID."\"] > .wbbBoard > .icon {\n";
				
				if ($board->isBoard()) {
					if ($board->icon || $board->iconColor) {
						$fileContent .= "\t\t&.icon-folder-close-alt::before {\n";
						
						if ($board->icon) {
							$fileContent .= "\t\t\tcontent: @".$board->icon.";\n";
						}
						if ($board->iconColor) {
							$fileContent .= "\t\t\tcolor: ".$board->iconColor.";\n";
						}
						
						$fileContent .= "\t\t}\n";
					}
					
					if ($board->iconNew || $board->iconNewColor) {
						$fileContent .= "\t\t&.icon-folder-close::before {\n";
						
						if ($board->iconNew) {
							$fileContent .= "\t\t\tcontent: @".$board->iconNew.";\n";
						}
						if ($board->iconNewColor) {
							$fileContent .= "\t\t\tcolor: ".$board->iconNewColor.";\n";
						}
						
						$fileContent .= "\t\t}\n";
					}
				}
				else if ($board->isExternalLink()) {
					if ($board->icon || $board->iconColor) {
						$fileContent .= "\t\t&.icon-globe::before {\n";
						
						if ($board->icon) {
							$fileContent .= "\t\t\tcontent: @".$board->icon.";\n";
						}
						if ($board->iconColor) {
							$fileContent .= "\t\t\tcolor: ".$board->iconColor.";\n";
						}
						
						$fileContent .= "\t\t}\n";
					}
				}
				
				$fileContent .= "\t}\n\n";
			}
		}
		
		// write file
		$styleFile = new File(Application::getDirectory('wbb').'style/boardIcon.less');
		$styleFile->write("// Do not edit this file manually! Manual changes will be overwriten.\n\n");
		
		if ($fileContent) {
			$styleFile->write(".wbbBoardList {\n");
			$styleFile->write(substr_replace($fileContent, '', -1));
			$styleFile->write("}\n");
		}
		
		$styleFile->close();
		
		EventHandler::getInstance()->fireAction($this, 'writeStyleFile');
		
		// reset stylesheets to apply changes
		StyleHandler::resetStylesheets();
	}
}
